### ISSUE TITLE
docker-compose 报错， 我在多个机子上都试了

### ISSUE THREAD

**Issue by tx991020** [douyu/juno-install#1]
-admin_1  | [2020-07-22 02:33:43] [info] replacing callback `gorm:row_query` from /home/www/server/go/pkg/mod/github.com/douyu/jupiter@v0.0.0-20200709073817-3e760e50d665/pkg/store/gorm/orm.go:118  
juno-admin_1  | 2020-07-22 02:33:43.8977573 +0000 UTC m=+0.057774201 write error: can't rename log file: rename / /.2020-07-22T02-33-43.897: device or resource busy
juno-admin_1  | time="2020-07-22T02:33:43Z" level=panic msg="Read Resource File Failed: open ./config/resource.yaml: no such file or directory"
juno-admin_1  | 1595385223      ERROR   recover                                 {"mod": "xgo", "errError": "json: unsupported type: func([]string)", "line": "/home/www/server/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259"}
juno-admin_1  | 2020-07-22 02:33:43.903784 +0000 UTC m=+0.063792501 write error: can't rename log file: rename / /.2020-07-22T02-33-43.903: device or resource busy
juno-admin_1  | panic: start up error: github.com/douyu/juno/internal/app/adminengine.(*Admin).initInvoker-fm:259: &{Logger:0xc00019c000 Data:map[] Time:2020-07-22 02:33:43.9019219 +0000 UTC m=+0.061927001 Level:panic Caller:<nil> Message:Read Resource File Failed: open ./config/resource.yaml: no such file or directory Buffer:<nil> Context:<nil> err:}
juno-admin_1  |

**Comment by sysulq** [comment]
麻烦再试下看看
