### ISSUE TITLE
docker-compose部署成功，初始化失败。

### ISSUE THREAD

**Issue by ryanbuu** [douyu/juno-install#16]
您好，我在尝试使用docker-compose部署时，```docker-compose --build -d```执行无误，下一步在初始化数据的时候，容器内部提示找不到```docker_juno_init.sh```这个脚本，麻烦有空时帮忙看下，感恩。

**Comment by ryanbuu** [comment]
我下载到的 ```ghcr.io/douyu/juno-admin```哈希为```sha256:d1ebd24157b60527f52641b7460e898d56e66207fe9499f9d0b7cf757e911a80```，再次表示感谢。

**Comment by sysulq** [comment]
@q1angch0u 收到，建议使用基于这个项目来搭建本地环境，已经不需要手动跑脚本了，这个项目会逐步废弃了

https://github.com/douyu/jupiter-layout

如果有问题，也欢迎到对应仓库提ISSUE，感谢

**Comment by ryanbuu** [comment]
@hnlq715 好的，辛苦回复，我去试试。
