### ISSUE TITLE
./install.sh: line 54: .: init.sh: file not found

### ISSUE THREAD

**Issue by harrywu001** [douyu/juno-install#2]
sh ./install.sh 
Install Env [y/n]: y
Install MySQL [y/n]: n
Install Etcd [y/n]: y
Install Prometheus [y/n]: y
Install Golang [y/n]: n
Install Grafana Database [y/n]: y
Install Grafana [y/n]: y
Install Juno Database [y/n]: y
Install Juno Mock [y/n]: y
Install Juno Admin [y/n]: y
Install Juno Agent [y/n]: y
Install Pprof [y/n]: y
Start the installation [y/n]: y
./install.sh: line 54: .: init.sh: file not found

**Comment by sysulq** [comment]
麻烦再基于docker-compose尝试下
