### ISSUE TITLE
Windows10安装时会出现的问题，踩坑.

### ISSUE THREAD

**Issue by younglifestyle** [douyu/juno-install#3]
踩坑1：在Windows下git clone，git bash会自动转换文件换行符从LF到CRLF，这会导致运行shell脚本报错。
解决：bash安装时，关闭自动转换功能. [参考](https://github.com/cssmagic/blog/issues/22)

踩坑2：不要使用git-bash进行安装，否则会出现：
![image](https://user-images.githubusercontent.com/19261307/90119872-b597b600-dd8c-11ea-988e-eafdb90c9aba.png)

**Comment by sysulq** [comment]
建议基于docker-compose再尝试下
