### ISSUE TITLE
docker-compose 安装方式报错,文件下载不到

### ISSUE THREAD

**Issue by huliang66** [douyu/juno-install#9]
ERROR: Service 'juno-admin' failed to build: The command '/bin/sh -c wget -P /root/juno http://jupiter.douyu.com/download/${JUNO_VERSION}/juno_data_${JUNO_VERSION}.tar.gz &&     cd /root/juno && tar xvf juno_data_${JUNO_VERSION}.tar.gz' returned a non-zero code: 5

https://jupiter.douyu.com/download/0.2.0/juno_data_0.2.0.tar.gz
这个文件是删除了吗?

**Comment by sysulq** [comment]
感谢反馈，近期会修复这个问题

**Comment by sysulq** [comment]
@huliang66 这个问题已修复，可以再基于docker-compose来试下
